spring.application.name=atlascommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/atlasdb
spring.datasource.username=atlas
spring.datasource.password=atlas123

spring.jpa.hibernate.ddl-auto=update